name: Build and Check PKGBUILDS

on: [push]

jobs:
  duplicacy-web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build and Check duplicacy-web
        uses: edlanglois/pkgbuild-action@v1
        with:
          # Relative path to directory containing the PKGBUILD file.
          pkgdir: "duplicacy-web"
  python-akro:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build and Check python-akro
        uses: edlanglois/pkgbuild-action@v1
        with:
          # Relative path to directory containing the PKGBUILD file.
          pkgdir: "python-akro"
          # Support AUR dependencies if nonempty.
          aurDeps: 1
  python-daemoniker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build and Check python-daemoniker
        uses: edlanglois/pkgbuild-action@v1
        with:
          # Relative path to directory containing the PKGBUILD file.
          pkgdir: "python-daemoniker"
  python-minerl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build and Check python-minerl
        uses: edlanglois/pkgbuild-action@v1
        with:
          # Relative path to directory containing the PKGBUILD file.
          pkgdir: "python-minerl"
          # Support AUR dependencies if nonempty.
          aurDeps: 1
  python-seed-isort-config:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build and Check python-seed-isort-config
        uses: edlanglois/pkgbuild-action@v1
        with:
          # Relative path to directory containing the PKGBUILD file.
          pkgdir: "python-seed-isort-config"
          # Support AUR dependencies if nonempty.
          aurDeps: 1
