# Build and check PKGBUILDS

name: CI

on: [push]

jobs:
  python-seed-isort-config:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        
      - name: Build and Check python-seed-isort-config
        uses: edlanglois/pkgbuild-action@v1
        with:
          # Relative path to directory containing the PKGBUILD file.
          pkgdir: "python-seed-isort-config"
